### ISSUE TITLE
Enforce using rems/ems in stylesheets

### ISSUE THREAD

**Issue by alisonhall** [PublicisSapient/enable-a11y#153]
We would like to have a linting/formatting rule to help enforce using responsive units (rems or ems) in our styles. This would help ensure code quality and help make sure that new code is responsive.

One way to do this may be to include the stylelint package in our code and include the [stylelint-rem-over-px](https://www.npmjs.com/package/stylelint-rem-over-px) plugin. If using this approach, we would need to make sure that stylelint doesn't conflict with our existing prettier and eslint settings. [stylelint-config-prettier](https://github.com/prettier/stylelint-config-prettier) may help with that.

We should investigate if there are better or easier ways to enforce this rule.

**Comment by seyilonge-ps** [comment]
- [ ] Clear linter warnings
- [ ] Add linter rules for rems/ems

**Comment by seyilonge-ps** [comment]
Stylelint does not exist in the project currently. It will have to be installed first before this plugin can be used within the project. I have opened a ticket #196 which has to be completed before this issue is resolved.

Tasks
- [ ] #196 
- [ ] Add [stylelint-rem-over-px](https://www.npmjs.com/package/stylelint-rem-over-px) plugin
- [ ] Configure plugin
- [ ] Fix errors

**Comment by seyilonge-ps** [comment]
> Stylelint does not exist in the project currently. It will have to be installed first before this plugin can be used within the project. I have opened a ticket #196 which has to be completed before this issue is resolved.
> 
> Tasks
> 
> * [x]  [Install and Configure Stylelint #196](https://github.com/PublicisSapient/enable-a11y/issues/196)
> * [ ]  Add [stylelint-rem-over-px](https://www.npmjs.com/package/stylelint-rem-over-px) plugin
> * [ ]  Configure plugin
> * [x]  Fix errors

The plugin [stylelint-rem-over-px](https://www.npmjs.com/package/stylelint-rem-over-px) was eventually ditched in PR #204 for the `stylelint` rule `declaration-property-unit-allowed-list` which provided more flexibility and control, and less overhead since it's already part of `stylelint`.
