### ISSUE TITLE
misaligned the meter component listing

### ISSUE THREAD

**Issue by Neha-Singla** [PublicisSapient/enable-a11y#170]
Meter component is listed with the animated content and the image is distorted.

<img width="1789" alt="Screenshot 2024-07-17 at 12 48 29 PM" src="https://github.com/user-attachments/assets/a8b3746b-d3ea-4f28-860f-79c70195a9eb">

**Comment by zoltan-dulac** [comment]
This is no longer valid after the redesign. Closing.
