### ISSUE TITLE
Update .nvmrc file with correct Node Version

### ISSUE THREAD

**Issue by seyilonge-ps** [PublicisSapient/enable-a11y#195]
The Node version in the `.nvmrc` file shows `20.4.0` while the `README.md` file has `20.11.0`. Running `nvm use` followed by `npm clean-install` results in errors.

Running `nvm list` provides a list of Node versions shown below
<img width="1687" alt="Screenshot 2024-08-09 at 10 56 21 AM" src="https://github.com/user-attachments/assets/4c3c7b9a-8a7e-4929-9929-effc9e142d09">

Version `20.11.0` in the `README.md` file is not listed. Best to use the most recent version in the list closest to the one specified in the `README.md` file, which is version `20.15.0`.

Steps to fix:
- [ ] Update Node version specified in the `.nvmrc` file to `20.15.0`
- [ ] Update Node version in the `README.md` file to `20.15.0`
- [ ] Add unit test to ensure the node version in the `README.md` matches the one in the `.nvmrc`

**Comment by zoltan-dulac** [comment]
Can you add to the steps to fix "Make unit test to ensure the node version in the README matches the one in the .nvmrc?  I'm sure this will happen again if we don't fix this.  

Thanks for finding this and opening a ticket for it.
