### ISSUE TITLE
Switch aria-describedby pointing to unexistant ID

### ISSUE THREAD

**Issue by zoltan-dulac** [PublicisSapient/enable-a11y#36]
As @noetibbl reported to me, the aria-describedby in the switch doesn't always point to the right state label.

**Comment by seyilonge-ps** [comment]
Issue actually occurs when you perform a toggle like click by clicking the "on" section of the `switch` button whenthe page loads to switch off, and without moving your cursor away, click the "on" section again to toggle back on.
