### ISSUE TITLE
Fix the jest tests so that they can be run concurrently

### ISSUE THREAD

**Issue by alisonhall** [PublicisSapient/enable-a11y#53]
The jest tests are not reliable if they run concurrently, and usually about ⅔ of them fail for me. They work properly when run one at a time. The `--runInBand` arg when running jest tests and `"maxConcurrency": 1` jest config property should ideally not be needed, but until the tests are made to be more reliable when running in parallel, this properties are needed.

There is likely some issue around tests not being cleaned up properly or something being used/modified in multiple tests at the same time.

**Comment by zoltan-dulac** [comment]
Doing this may cause more problems than it solves.  Let's close this for now.  We can revisit if we think it's an issue.
